spring.application.name=dragon-monster

# H2 Console Configuration
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Database Connection (H2 Memory)
spring.datasource.url=jdbc:h2:mem:dragondb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate Configuration
#spring.jpa.hibernate.ddl-auto=update
create-drop
spring.jpa.show-sql=true
server.port=8081    